title: Alexie Millikin Final Project for Earth Analytics
description: A project portfolio website 

logo: /img/Millikin_headshot.jpeg

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
